# Generated by Django 3.0.9 on 2020-08-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonvegchinese',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nonvegindian',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vegchinese',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vegindian',
            name='price',
            field=models.FloatField(),
        ),
    ]
