# Generated by Django 3.0.9 on 2020-08-16 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0002_auto_20200814_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonveg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuapp.NonvegIndian')),
                ('veg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuapp.VegIndian')),
            ],
        ),
        migrations.CreateModel(
            name='Chinese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonveg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuapp.NonvegChinese')),
                ('veg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuapp.VegChinese')),
            ],
        ),
    ]
