# Generated by Django 3.0.9 on 2020-08-16 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0003_chinese_indian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indian',
            name='nonveg',
        ),
        migrations.RemoveField(
            model_name='indian',
            name='veg',
        ),
        migrations.DeleteModel(
            name='Chinese',
        ),
        migrations.DeleteModel(
            name='Indian',
        ),
    ]
